---
#
# file:  playbooks/roles/host_instance/tasks/main.yml
#

- name: Add docker gpg key
  apt_key:
    keyserver: "{{ docker_gpg_keyserver }}"
    id: "{{ docker_gpg_id }}"

- name: Add docker repo
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present

# need this for installing correct version of linux-image-extra
- name: Read uname
  shell: uname -r
  register: uname_output

- name: install packages
  package:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ role_packages }}"

- name: add bonding to kernel modules
  template:
    src: "{{ template_dir }}/etc/modules"
    dest: "/etc/modules"
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: interfaces bonding setup compute
  template:
    src: "{{ template_dir }}/etc/network/interfaces.compute"
    dest: "/etc/network/interfaces"
    owner: root
    group: root
    mode: 0644
    backup: yes
  when: host == compute-01

- name: interfaces bonding setup docker
  template:
    src: "{{ template_dir }}/etc/network/interfaces.docker"
    dest: "/etc/network/interfaces"
    owner: root
    group: root
    mode: 0644
    backup: yes
  when: host == docker-01

- name: resolv.conf
  template:
    src: "{{ template_dir }}/etc/resolv.conf"
    dest: "/etc/resolv.conf"
    owner: root
    group: root
    mode: 0644

- name: Run dmsetup for Ubuntu 16.04
  command: dmsetup mknodes
