---
#
# file: handlers/main.yml
#

####
# System network handlers
####
- name: systemctl daemon-reload
  command: systemctl daemon-reload

- name: restart iptables
  service:
    name: iptables
    state: restarted

- name: restart network
  service:
    name: network
    state: restarted

- name: restart sshd
  service:
    name: sshd
    state: restarted
