---
  # TODO: We currently use virsh-install to create the domain
  #       but this means we are restricted to the API designated
  #       by the bin. With XML we have ALL the control, at the
  #       cost of complexity

  # THIS IS NOT CURRENTLY USED, AS VIRSH-INSTALL WILL SUFFICE
- name: create_domain | template
  template:
    dest: "/tmp/{{ libvirt_result_domain_name }}.xml"
    src: "machine.xml.j2"

- name: create_domain | define
  command: "virsh define /tmp/{{ libvirt_result_domain_name }}.xml"

- name: create_domain | start
  command: "virsh start {{ libvirt_result_domain_name }}"
